### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jernejbanevec** [katarinabrilej/looking.si#1]
Pozdrav!
Pregledal sem vajin ER diagram in imam naslednje vprašanje. Pri entiteti _LOKACIJA_ bodo atributi _SMUČIŠČE, PLAŽA, ZNAMENITOSTI, itd._ imeli vrednosti `TRUE/FALSE`? Morda bi bilo smiselno kot atribut dodati tudi ime lokacije ali ime najbližjega večjega mesta.

Mimogrede, mape `_pycache_` na repozitoriju ne potrebujeta. Zato to mapo iz repozitorija lahko odstranita in z `.gitignore` poskrbita, da git te mape na repozitorij ne bo naložil ponovno.

**Comment by evadezelak** [comment]
Hvala za opozorilo. Sva popravili, bo sedaj uredu?
